### ISSUE TITLE
HttpRequest can't be used as a Controller parameter

### ISSUE THREAD

**Issue by dwursteisen** [bclozel/spring-boot-web-reactive#17] opened 2016-08-18 15:49 UTC
Using Spring boot web reactive, I wasn't be abble to get the `HttpRequest` as a parameter in a method from a `Controller`

```
@Controller
public class HelloWorldController {

	@ResponseBody()
	@RequestMapping(value = "/nexus/**", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE, method = RequestMethod.GET)
	public Single<ResponseEntity<?>> hello(HttpRequest request) {
		return Single.just(new ResponseEntity("hello world !", HttpStatus.OK));
        }
}
```

To achieve this, I had to add an custom `RequestMappingHandlerAdapter` which detect the `HttpRequest` class and then resolve it.

```
@Configuration
public class HelloWorldConfiguration {
      @Bean
	public RequestMappingHandlerAdapter adapter() {
		RequestMappingHandlerAdapter requestMappingHandlerAdapter = new RequestMappingHandlerAdapter();
		requestMappingHandlerAdapter.setCustomArgumentResolvers(Collections.singletonList(new HandlerMethodArgumentResolver() {
			@Override public boolean supportsParameter(MethodParameter methodParameter) {
				return HttpRequest.class.isAssignableFrom(methodParameter.getParameterType());
			}

			@Override public Mono<Object> resolveArgument(MethodParameter methodParameter, ModelMap modelMap, ServerWebExchange serverWebExchange) {
				return Mono.just(serverWebExchange.getRequest());
			}
		}));
		return requestMappingHandlerAdapter;
	}

}
```

- Is `HttpRequest` can be resolved, by default ? 
- Is my usage of `HttpRequest` is correct ? (I need it to get the full request uri)
- Is it expected to have to declare a custumer argument resolvers to achieve this ? (or is not expected and I may have found a bug ?)

Regards

**Comment by aminmc** [comment] 2016-08-21 15:42
I've just come across this and applied your configuration which fixes the HttpRequest but I'm seeing the same exception for other parameters in my Rest controllers (custom objects annotated with @RequestBody).

Anyone else seeing this?

**Comment by bclozel** [comment] 2016-08-22 14:20
@dwursteisen You're right, this is missing from the default resolvers. I've created [SPR-14612](https://jira.spring.io/browse/SPR-14612) to reflect that. Thanks!

@aminmc `@RequestBody` annotated parameters should be resolved by the `RequestBodyArgumentResolver`. Could you explain how to reproduce this or better, create a sample project that shows this problem? You can then comment here or create a new issue on https://jira.spring.io (component: reactive).

**Closed by bclozel** 2016-08-22 14:20 UTC

**Comment by aminmc** [comment] 2016-08-22 15:08
[reactiveweb.zip](https://github.com/bclozel/spring-boot-web-reactive/files/430468/reactiveweb.zip)

Hi

I've added a sample project. If you run ReactivewebApplication and then use postman to do a post to http://localhost:8080/home with the following:
```json
{
    "name" : "Amin",
    "colour" : "Red"
}
```
you should see an exception in the console.  Hope this helps.

**Comment by bclozel** [comment] 2016-08-22 16:50
@aminmc Removing the custom `HelloWorldConfiguration` fixes things, so that argument resolver is working properly.

I'd argue that you shouldn't create `RequestMappingHandlerAdapter` yourself; I've created #18 and I'll look into ways to properly extend that bean.

Worst case scenario, a `BeanPostProcessor` would be a better choice.

**Comment by aminmc** [comment] 2016-08-22 16:54
@bclozel Ok. I reused the HelloWorldConfiguration because I needed the HttpRequest to perform some other functions.  I'll wait for SPR-14612.

**Comment by bclozel** [comment] 2016-09-02 07:26
This has been fixed with SPR-14658, you can now inject `ServerHttpRequest`, `ServerHttpResponse` and `ServerWebExchange`, `WebSession` and `HttpMethod`.
